tasks:
  - name: init project
    init: npm init -y
    command: echo 'start script'
  - name: install express
    init: npm install --save express
    command: touch index.js

ports:
  - port: 3000
    onOpen: open-preview
